export const FIND_JOB_BY_ID_REQUEST='FIND_JOB_BY_ID_REQUEST'
export const FIND_JOB_BY_ID_SUCCESS='FIND_JOB_BY_ID_SUCCESS'
export const FIND_JOB_BY_ID_FAILURE='FIND_JOB_BY_ID_FAILURE'

export const FIND_JOB_BY_JOBTITLE_REQUEST='FIND_JOB_BY_JOBTITLE_REQUEST'
export const FIND_JOB_BY_JOBTITLE_SUCCESS='FIND_JOB_BY_JOBTITLE_SUCCESS'
export const FIND_JOB_BY_JOBTITLE_FAILURE='FIND_JOB_BY_JOBTITLE_FAILURE'



